#!/usr/bin/env python
import RPi.GPIO as GPIO
import time

# breadboard setup
GPIO. setmode (GPIO.BOARD)
GPIO. setwarnings (False)

# assign pin number for Touch Switch; pin 31 = GPIO 6
touch_pin =31

# set Touch Switch pin's mode as input
GPIO.setup(touch_pin,GPIO.IN)

# create infinite loop that reads Touch Switch input
while True:
	if GPIO.input (touch_pin) == 0:
		# add code to turn off a sensor
		GPIO.output(led_pin,False)
	if GPIO.input (touch_pin) == 1:
		# add code to turn on a sensor 
		GPIO.output(led_pin,True)
